### PR TITLE
OC-9691: Bring OSC builds up to date

### PR DESCRIPTION
**Pull request by hosh**
- Widen cookbook versions

Related:
- https://github.com/opscode/chef_wm/pull/80
- https://github.com/opscode/omnibus-chef-server/pull/17

### CODE REVIEW

**Comment by seth** [comment]
The view reformatting is separate from the column widening, right? I'd prefer to see those as two separate commits and for the commit that does produce a non-backwards compatible schema to have more discussion of this in the commit comment. This is something we will need to come back to and provide schema upgrade tooling. This fix gives us a build we can work with.

**Comment by hosh** [comment]
Summary of discussion during standup:

I ported @oferrigni migrations elsewhere, where the views had to be dropped and recreated after the column widening. This change was before I found out that the views were reconstructed the same. Further, in this case, this is starting a schema from scratch, so it is not necessary to recreate the views. I have rebased the patch so it only widen the column without changing the views.

**Comment by seth** [comment]
Change looks good, but commit message needs more detail on why the change as well as the need for migration tooling as something to come back for.

**Comment by seth** [comment]
Good to merge (since one commit, skip the merge commit would be my preference)

**Pull request merged**
