### PR TITLE
OC-1409: Refactored chef_sql:fetch_objects() to fetch_object_names()

### PR DESCRIPTION
**Pull request by hosh**
chef_sql:fetch_objects returns a list of object names, so it has been renamed to fetch_object_names()

### CODE REVIEW

**Comment by hosh** [comment]
@seth @christophermaier Took out comments referring to refactoring.

**Comment by christophermaier** [comment]
I was actually just talking about editing the comments.  I guess this works too.

**Comment by hosh** [comment]
Oh. Hmmm. I'm not sure what I would edit them to.

**Comment by seth** [comment]
I'm +1 on just removing. If you've verified that consumers of chef_db aren't calling the API that changed, then I think this is good to merge.

**Pull request merged**
